var listaCartas = [
     {
        id: 1,
        code : 'SOPH',
         artista: "pH-1",
         grupo: "Soloist",
         versao: 1,
         raridade: 1,
         release: "23/01/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/pH-1-1-V1.png',
         new: false
     },
     {
        id: 2, 
        code : 'SOLE',
         artista: "SOLE",
         grupo: "Soloist",
         versao: 1,
         raridade: 1,
         release: "23/01/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/SOLE-1-V1.png',
         new: false
     },
     {
        id: 3, 
        code : 'LO2HE5',
         artista: "Heejin",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Heejin-5-V2.gif',
         new: false
     },
     {
        id: 4, 
        code : 'LO2HY5',
         artista: "Hyunjin",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Hyunjin-5-V2.gif',
         new: false
     },
     {
        id: 5, 
        code : 'LO2HA5',
         artista: "Haseul",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Haseul-5-V2.gif',
         new: false
     },
     {
        id: 6, 
        code : 'LO2YE5',
         artista: "Yeojin",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Yeojin-5-V2.gif',
         new: false
     },
     {
        id: 7, 
        code : 'LO2VI5',
         artista: "Vivi",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Vivi-5-V2.gif',
         new: false
     },
     {
        id: 8, 
        code : 'LO2KI5',
         artista: "Kim Lip",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/KimLip-5-V2.gif',
         new: false
     },
     {
        id: 9, 
        code : 'LO2JI5',
         artista: "Jinsoul",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Jinsoul-5-V2.gif',
         new: false
     },
     {
        id: 10, 
        code : 'LO2CY5',
         artista: "Choerry",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Choerry-5-V2.gif',
         new: false
     },
     {
        id: 11, 
        code : 'LO2YV5',
         artista: "Yves",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Yves-5-V2.gif',
         new: false
     },
     {
        id: 12, 
        code : 'LO2CH5',
         artista: "Chuu",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Chuu-5-V2.gif',
         new: false
     },
     {
        id: 13, 
        code : 'LO2GO5',
         artista: "Gowon",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/Gowon-5-V2.gif',
         new: false
     },
     {
        id: 14, 
        code : 'LO2OL5',
         artista: "Olivia Hye",
         grupo: "LOONA",
         versao: 2,
         raridade: 5,
         release: "04/02/2022",
         link: 'https://cdn.koreaverse.com/LOONA/Original/OliviaHye-5-V2.gif',
         new: false
     },
     {
        id: 15, 
        code : 'HVAL',
         artista: "Alice",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 1,
         release: "05/02/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Alice-1-V1.png',
         new: false
     },
     {
        id: 16, 
        code : 'HVLI',
         artista: "Lime",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 1,
         release: "05/02/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Lime-1-V1.png',
         new: false
     },
     {
        id: 17, 
        code : 'HVNA',
         artista: "Nara",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 1,
         release: "05/02/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Nara-1-V1.png',
         new: false
     },
     {
        id: 18, 
        code : 'HVSE',
         artista: "Seoyoungce",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 1,
         release: "05/02/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Seoyoung-1-V1.png',
         new: false
     },
     {
        id: 19, 
        code : 'HVYE',
         artista: "Yeoreum",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 1,
         release: "05/02/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Yeoreum-1-V1.png',
         new: false
     },
     {
        id: 20, 
        code : 'HVYO',
         artista: "Yooyoung",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 1,
         release: "05/02/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Yooyoung-1-V1.png',
         new: false
     },
     {
        id: 21, 
        code : 'NMBA',
         artista: "Bae",
         grupo: "NMIXX",
         versao: 1,
         raridade: 1,
         release: "11/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Bae-1-V1.png',
         new: false
     },
     {
        id: 22, 
        code : 'NMHA',
         artista: "Haewon",
         grupo: "NMIXX",
         versao: 1,
         raridade: 1,
         release: "11/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Haewon-1-V1.png',
         new: false
     },
     {
        id: 23, 
        code : 'NMJI',
         artista: "Jinni",
         grupo: "NMIXX",
         versao: 1,
         raridade: 1,
         release: "11/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Jinni-1-V1.png',
         new: false
     },
     {
        id: 24, 
        code : 'NMJW',
         artista: "Jiwoo",
         grupo: "NMIXX",
         versao: 1,
         raridade: 1,
         release: "11/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Jiwoo-1-V1.png',
         new: false
     },
     {
        id: 25, 
        code : 'NMKY',
         artista: "Kyujin",
         grupo: "NMIXX",
         versao: 1,
         raridade: 1,
         release: "11/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Kyujin-1-V1.png',
         new: false
     },
     {
        id: 26, 
        code : 'NMLI',
         artista: "Lily",
         grupo: "NMIXX",
         versao: 1,
         raridade: 1,
         release: "11/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Lily-1-V1.png',
         new: false
     },
     {
        id: 27, 
        code : 'NMSU',
         artista: "Sullyoon",
         grupo: "NMIXX",
         versao: 1,
         raridade: 1,
         release: "11/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Sullyoon-1-V1.png',
         new: false
     },
     {
        id: 28, 
        code : 'TLBY',
         artista: "Baek Yerin",
         grupo: "The Volunteers",
         versao: 1,
         raridade: 1,
         release: "12/02/2022",
         link: 'https://cdn.koreaverse.com/TheVolunteers/Original/BaekYerin-1-V1.png',
         new: false
     },
     {
        id: 29, 
        code : 'TLCH',
         artista: "Chiheon",
         grupo: "The Volunteers",
         versao: 1,
         raridade: 1,
         release: "12/02/2022",
         link: 'https://cdn.koreaverse.com/TheVolunteers/Original/Chiheon-1-V1.png',
         new: false
     },
     {
        id: 30, 
        code : 'TLCL',
         artista: "Cloud",
         grupo: "The Volunteers",
         versao: 1,
         raridade: 1,
         release: "12/02/2022",
         link: 'https://cdn.koreaverse.com/TheVolunteers/Original/Cloud-1-V1.png',
         new: false
     },
     {
        id: 31, 
        code : 'TLJO',
         artista: "Jonny",
         grupo: "The Volunteers",
         versao: 1,
         raridade: 1,
         release: "12/02/2022",
         link: 'https://cdn.koreaverse.com/TheVolunteers/Original/Jonny-1-V1.png',
         new: false
     },
     {
        id: 32, 
        code : 'NMBA2',
         artista: "Bae",
         grupo: "NMIXX",
         versao: 1,
         raridade: 2,
         release: "19/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Bae-2-V1.png',
         new: false
     },
     {
        id: 33, 
        code : 'NMHA2',
         artista: "Haewon",
         grupo: "NMIXX",
         versao: 1,
         raridade: 2,
         release: "19/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Haewon-2-V1.png',
         new: false
     },
     {
        id: 34, 
        code : 'NMJI2',
         artista: "Jinni",
         grupo: "NMIXX",
         versao: 1,
         raridade: 2,
         release: "19/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Jinni-2-V1.png',
         new: false
     },
     {
        id: 35, 
        code : 'NMJW2',
         artista: "Jiwoo",
         grupo: "NMIXX",
         versao: 1,
         raridade: 2,
         release: "19/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Jiwoo-2-V1.png',
         new: false
     },
     {
        id: 36, 
        code : 'NMKY2',
         artista: "Kyujin",
         grupo: "NMIXX",
         versao: 1,
         raridade: 2,
         release: "19/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Kyujin-2-V1.png',
         new: false
     },
     {
        id: 37, 
        code : 'NMLI2',
         artista: "Lily",
         grupo: "NMIXX",
         versao: 1,
         raridade: 2,
         release: "19/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Lily-2-V1.png',
         new: false
     },
     {
        id: 38, 
        code : 'NMSU2',
         artista: "Sullyoon",
         grupo: "NMIXX",
         versao: 1,
         raridade: 2,
         release: "19/02/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Sullyoon-2-V1.png',
         new: false
     },
     {
        id: 39, 
        code : 'SOYUN',
         artista: "YUNHWAY",
         grupo: "Soloist",
         versao: 1,
         raridade: 1,
         release: "06/03/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/YUNHWAY-1-V1.png',
         new: false
     },
     {
        id: 40, 
        code : 'EHDJ',
         artista: "DJ Tukutz",
         grupo: "EPIK HIGH",
         versao: 1,
         raridade: 1,
         release: "11/03/2022",
         link: 'https://cdn.koreaverse.com/EpikHigh/Original/DJTukutz-1-V1.png',
         new: false
     },
     {
        id: 41, 
        code : 'EHMJ',
         artista: "Mithra Jin",
         grupo: "EPIK HIGH",
         versao: 1,
         raridade: 1,
         release: "11/03/2022",
         link: 'https://cdn.koreaverse.com/EpikHigh/Original/MithraJin-1-V1.png',
         new: false
     },
     {
        id: 42, 
        code : 'EHTA',
         artista: "Tablo",
         grupo: "EPIK HIGH",
         versao: 1,
         raridade: 1,
         release: "11/03/2022",
         link: 'https://cdn.koreaverse.com/EpikHigh/Original/Tablo-1-V1.png',
         new: false
     },
     {
        id: 43, 
        code : 'SOKS',
         artista: "Kim Sejeong",
         grupo: "Soloist",
         versao: 1,
         raridade: 1,
         release: "26/03/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/KimSejeong-1-V1.png',
         new: false
     },
     {
        id: 44, 
        code : 'WE3LJ',
         artista: "Jaehee",
         grupo: "Weeekly",
         versao: 3,
         raridade: 1,
         release: "27/03/2022",
         link: 'https://cdn.koreaverse.com/Weeekly/Original/LeeJaehee-1-V3.png',
         new: false
     },
     {
        id: 45, 
        code : 'WE3JI',
         artista: "Jihan",
         grupo: "Weeekly",
         versao: 3,
         raridade: 1,
         release: "27/03/2022",
         link: 'https://cdn.koreaverse.com/Weeekly/Original/Jihan-1-V3.png',
         new: false
     },
     {
        id: 46, 
        code : 'WE3SJ',
         artista: "Jiyoon",
         grupo: "Weeekly",
         versao: 3,
         raridade: 1,
         release: "27/03/2022",
         link: 'https://cdn.koreaverse.com/Weeekly/Original/ShinJiyoon-1-V3.png',
         new: false
     },
     {
        id: 47, 
        code : 'WE3MO',
         artista: "Monday",
         grupo: "Weeekly",
         versao: 3,
         raridade: 1,
         release: "27/03/2022",
         link: 'https://cdn.koreaverse.com/Weeekly/Original/Monday-1-V3.png',
         new: false
     },
     {
        id: 48, 
        code : 'WE3PS',
         artista: "Soeun",
         grupo: "Weeekly",
         versao: 3,
         raridade: 1,
         release: "27/03/2022",
         link: 'https://cdn.koreaverse.com/Weeekly/Original/ParkSoeun-1-V3.png',
         new: false
     },
     {
        id: 49, 
        code : 'WE3LS',
         artista: "Soojin",
         grupo: "Weeekly",
         versao: 3,
         raridade: 1,
         release: "27/03/2022",
         link: 'https://cdn.koreaverse.com/Weeekly/Original/LeeSoojin-1-V3.png',
         new: false
     },
     {
        id: 50, 
        code : 'WE3ZO',
         artista: "Zoa",
         grupo: "Weeekly",
         versao: 3,
         raridade: 1,
         release: "27/03/2022",
         link: 'https://cdn.koreaverse.com/Weeekly/Original/Zoa-1-V3.png',
         new: false
     },
     {
        id: 51, 
        code : '2N2BO',
         artista: "Bom",
         grupo: "2NE1",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/2NE1/Original/Bom-1-V2.png',
         new: false
     },
     {
        id: 52, 
        code : '2N2CL',
         artista: "CL",
         grupo: "2NE1",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/2NE1/Original/CL-1-V2.png',
         new: false
     },
     {
        id: 53, 
        code : '2N2DR',
         artista: "Dara",
         grupo: "2NE1",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/2NE1/Original/Dara-1-V2.png',
         new: false
     },
     {
        id: 54, 
        code : '2N2MI',
         artista: "Minzy",
         grupo: "2NE1",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/2NE1/Original/Minzy-1-V2.png',
         new: false
     },
     {
        id: 55, 
        code : 'AP2BO',
         artista: "Bomi",
         grupo: "Apink",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/Apink/Original/Bomi-1-V2.png',
         new: false
     },
     {
        id: 56, 
        code : 'AP2CH',
         artista: "Chorong",
         grupo: "Apink",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/Apink/Original/Chorong-1-V2.png',
         new: false
     },
     {
        id: 57, 
        code : 'AP2EU',
         artista: "Eunji",
         grupo: "Apink",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/Apink/Original/Eunji-1-V2.png',
         new: false
     },
     {
        id: 58, 
        code : 'AP2HA',
         artista: "Hayoung",
         grupo: "Apink",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/Apink/Original/Hayoung-1-V2.png',
         new: false
     },
     {
        id: 59, 
        code : 'AP2NA',
         artista: "Naeun",
         grupo: "Apink",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/Apink/Original/Naeun-1-V2.png',
         new: false
     },
     {
        id: 60, 
        code : 'AP2NN',
         artista: "Namjoo",
         grupo: "Apink",
         versao: 2,
         raridade: 1,
         release: "02/04/2022",
         link: 'https://cdn.koreaverse.com/Apink/Original/Namjoo-1-V2.png',
         new: false
     },
     {
        id: 61, 
        code : 'SOKN',
         artista: "Kim Namjoo",
         grupo: "Soloist",
         versao: 1,
         raridade: 1,
         release: "09/04/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/KimNamjoo-1-V1.png',
         new: false
     },
     {
        id: 62, 
        code : 'L13HA',
         artista: "Haseul",
         grupo: "LOONA 1/3",
         versao: 1,
         raridade: 1,
         release: "09/04/2022",
         link: 'https://cdn.koreaverse.com/LOONA13/Original/Haseul-1-V1.png',
         new: false
     },
     {
        id: 63, 
        code : 'L13HE',
         artista: "Heejin",
         grupo: "LOONA 1/3",
         versao: 1,
         raridade: 1,
         release: "09/04/2022",
         link: 'https://cdn.koreaverse.com/LOONA13/Original/Heejin-1-V1.png',
         new: false
     },
     {
        id: 64, 
        code : 'L13HY',
         artista: "Hyunjin",
         grupo: "LOONA 1/3",
         versao: 1,
         raridade: 1,
         release: "09/04/2022",
         link: 'https://cdn.koreaverse.com/LOONA13/Original/Hyunjin-1-V1.png',
         new: false
     },
     {
        id: 65, 
        code : 'L13VI',
         artista: "Vivi",
         grupo: "LOONA 1/3",
         versao: 1,
         raridade: 1,
         release: "09/04/2022",
         link: 'https://cdn.koreaverse.com/LOONA13/Original/Vivi-1-V1.png',
         new: false
     },
     {
        id: 66, 
        code : 'SO2TY5',
         artista: "TAEYEON",
         grupo: "Soloist",
         versao: 2,
         raridade: 5,
         release: "29/04/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/TAEYEON-5-V2.gif',
         new: false
     },
     {
        id: 67, 
        code : 'NMBA3',
         artista: "Bae",
         grupo: "NMIXX",
         versao: 1,
         raridade: 3,
         release: "07/05/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Bae-3-V1.gif',
         new: false
     },
     {
        id: 68, 
        code : 'NMHA3',
         artista: "Haewon",
         grupo: "NMIXX",
         versao: 1,
         raridade: 3,
         release: "07/05/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Haewon-3-V1.gif',
         new: false
     },
     {
        id: 69, 
        code : 'NMJI3',
         artista: "Jinni",
         grupo: "NMIXX",
         versao: 1,
         raridade: 3,
         release: "07/05/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Jinni-3-V1.gif',
         new: false
     },
     {
        id: 70, 
        code : 'NMJW3',
         artista: "Jiwoo",
         grupo: "NMIXX",
         versao: 1,
         raridade: 3,
         release: "07/05/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Jiwoo-3-V1.gif',
         new: false
     },
     {
        id: 71, 
        code : 'NMKY3',
         artista: "Kyujin",
         grupo: "NMIXX",
         versao: 1,
         raridade: 3,
         release: "07/05/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Kyujin-3-V1.gif',
         new: false
     },
     {
        id: 72, 
        code : 'NMLI3',
         artista: "Lily",
         grupo: "NMIXX",
         versao: 1,
         raridade: 3,
         release: "07/05/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Lily-3-V1.gif',
         new: false
     },
     {
        id: 73, 
        code : 'NMSU3',
         artista: "Sullyoon",
         grupo: "NMIXX",
         versao: 1,
         raridade: 3,
         release: "07/05/2022",
         link: 'https://cdn.koreaverse.com/NMIXX/Original/Sullyoon-3-V1.gif',
         new: false
     },
     {
        id: 74, 
        code : 'HVAL2',
         artista: "Alice",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 2,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Alice-2-V1.png',
         new: false
     },
     {
        id: 75, 
        code : 'HVLI2',
         artista: "Lime",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 2,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Lime-2-V1.png',
         new: false
     },
     {
        id: 76, 
        code : 'HVNA2',
         artista: "Nara",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 2,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Nara-2-V1.png',
         new: false
     },
     {
        id: 77, 
        code : 'HVSE2',
         artista: "Seoyoungce",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 2,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Seoyoung-2-V1.png',
         new: false
     },
     {
        id: 78, 
        code : 'HVYE2',
         artista: "Yeoreum",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 2,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Yeoreum-2-V1.png',
         new: false
     },
     {
        id: 79, 
        code : 'HVYO2',
         artista: "Yooyoung",
         grupo: "Hello Venus",
         versao: 1,
         raridade: 2,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/HelloVenus/Original/Yooyoung-2-V1.png',
         new: false
     },
     {
        id: 80, 
        code : 'FICL',
         artista: "Cao Lu",
         grupo: "FIESTAR",
         versao: 1,
         raridade: 1,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/FIESTAR/Original/CaoLu-1-V1.png',
         new: false
     },
     {
        id: 81, 
        code : 'FIFE',
         artista: "Fei",
         grupo: "FIESTAR",
         versao: 1,
         raridade: 1,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/FIESTAR/Original/Fei-1-V1.png',
         new: false
     },
     {
        id: 82, 
        code : 'FIHY',
         artista: "Hyemi",
         grupo: "FIESTAR",
         versao: 1,
         raridade: 1,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/FIESTAR/Original/Hyemi-1-V1.png',
         new: false
     },
     {
        id: 83, 
        code : 'FILI',
         artista: "Linzy",
         grupo: "FIESTAR",
         versao: 1,
         raridade: 1,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/FIESTAR/Original/Linzy-1-V1.png',
         new: false
     },
     {
        id: 84, 
        code : 'FIYE',
         artista: "Yezi",
         grupo: "FIESTAR",
         versao: 1,
         raridade: 1,
         release: "20/05/2022",
         link: 'https://cdn.koreaverse.com/FIESTAR/Original/Yezi-1-V1.png',
         new: false
     },
     {
        id: 85, 
        code : 'SOKS2',
         artista: "Kim Sejeong",
         grupo: "Soloist",
         versao: 1,
         raridade: 2,
         release: "29/05/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/KimSejeong-2-V1.png',
         new: false
     },
     {
        id: 86, 
        code : 'VISI',
         artista: "SinB",
         grupo: "VIVIZ",
         versao: 1,
         raridade: 1,
         release: "11/06/2022",
         link: 'https://cdn.koreaverse.com/VIVIZ/Original/SinB-1-V1.png',
         new: true
     },
     {
        id: 87, 
        code : 'VIEU',
         artista: "Eunha",
         grupo: "VIVIZ",
         versao: 1,
         raridade: 1,
         release: "11/06/2022",
         link: 'https://cdn.koreaverse.com/VIVIZ/Original/Eunha-1-V1.png',
         new: true
     },
     {
        id: 88, 
        code : 'VIUM',
         artista: "Umji",
         grupo: "VIVIZ",
         versao: 1,
         raridade: 1,
         release: "11/06/2022",
         link: 'https://cdn.koreaverse.com/VIVIZ/Original/Umji-1-V1.png',
         new: true
     },
     {
        id: 89, 
        code : 'SOZT',
         artista: "Zion.T",
         grupo: "Soloist",
         versao: 1,
         raridade: 1,
         release: "11/06/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/Zion.T-1-V1.png',
         new: true
     },
     {
        id: 90, 
        code : 'SOKN2',
         artista: "Kim Namjoo",
         grupo: "Soloist",
         versao: 1,
         raridade: 2,
         release: "11/06/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/KimNamjoo-2-V1.png',
         new: true
     },
     {
        id: 91, 
        code : 'SOLE2',
         artista: "SOLE",
         grupo: "Soloist",
         versao: 1,
         raridade: 2,
         release: "11/06/2022",
         link: 'https://cdn.koreaverse.com/Soloists/Original/SOLE-2-V1.png',
         new: true
     },
]

export default listaCartas;